name: text

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - pip:
    - Flask==1.1.2
    - Jinja2==2.11.2
    - MarkupSafe==1.1.1
    - Pillow==8.0.1
    - Werkzeug==1.0.1
    - certifi==2020.11.8
    - chardet==3.0.4
    - click==7.1.2
    - idna==2.10
    - itsdangerous==1.1.0
    - numpy==1.19.4
    - opencv-python==4.4.0.46
    - pytesseract==0.3.6
    - requests==2.25.0
    - setuptools==50.3.2
    - urllib3==1.26.2